/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_csource_shmcache_ShmCache */

#ifndef _Included_org_csource_shmcache_ShmCache
#define _Included_org_csource_shmcache_ShmCache
#ifdef __cplusplus
extern "C" {
#endif
#undef org_csource_shmcache_ShmCache_TTL_NEVER_EXPIRED
#define org_csource_shmcache_ShmCache_TTL_NEVER_EXPIRED 0L
/*
 * Class:     org_csource_shmcache_ShmCache
 * Method:    doInit
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_csource_shmcache_ShmCache_doInit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_csource_shmcache_ShmCache
 * Method:    doDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_csource_shmcache_ShmCache_doDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_csource_shmcache_ShmCache
 * Method:    doSet
 * Signature: (JLjava/lang/String;[BI)V
 */
JNIEXPORT void JNICALL Java_org_csource_shmcache_ShmCache_doSet
  (JNIEnv *, jobject, jlong, jstring, jbyteArray, jint);

/*
 * Class:     org_csource_shmcache_ShmCache
 * Method:    doIncr
 * Signature: (JLjava/lang/String;JI)J
 */
JNIEXPORT jlong JNICALL Java_org_csource_shmcache_ShmCache_doIncr
  (JNIEnv *, jobject, jlong, jstring, jlong, jint);

/*
 * Class:     org_csource_shmcache_ShmCache
 * Method:    doGet
 * Signature: (JLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_csource_shmcache_ShmCache_doGet
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_csource_shmcache_ShmCache
 * Method:    doDelete
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_csource_shmcache_ShmCache_doDelete
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_csource_shmcache_ShmCache
 * Method:    doSetTTL
 * Signature: (JLjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_csource_shmcache_ShmCache_doSetTTL
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     org_csource_shmcache_ShmCache
 * Method:    doGetExpires
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_csource_shmcache_ShmCache_doGetExpires
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_csource_shmcache_ShmCache
 * Method:    doRemoveAll
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_csource_shmcache_ShmCache_doRemoveAll
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_csource_shmcache_ShmCache
 * Method:    doClear
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_csource_shmcache_ShmCache_doClear
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
